export const COUNTRY_FLAGS: { [key: string]: string } = {
    "United States": "🇺🇸",
    "Canada": "🇨🇦",
    "United Kingdom": "🇬🇧",
    "Australia": "🇦🇺",
    "Germany": "🇩🇪",
    "France": "🇫🇷",
    "Spain": "🇪🇸",
    "Italy": "🇮🇹",
    "Japan": "🇯🇵",
    "South Korea": "🇰🇷",
    "Netherlands": "🇳🇱",
    "Belgium": "🇧🇪",
    "Switzerland": "🇨🇭",
    "Austria": "🇦🇹",
    "Sweden": "🇸🇪",
    "Norway": "🇳🇴",
    "Denmark": "🇩🇰",
    "Finland": "🇫🇮",
    "Ireland": "🇮🇪",
    "Portugal": "🇵🇹",
    "Greece": "🇬🇷",
    "Poland": "🇵🇱",
    "India": "🇮🇳",
    "China": "🇨🇳",
    "Singapore": "🇸🇬",
    "Thailand": "🇹🇭",
    "Vietnam": "🇻🇳",
    "Malaysia": "🇲🇾",
    "Indonesia": "🇮🇩",
    "Philippines": "🇵🇭",
    "New Zealand": "🇳🇿",
    "Mexico": "🇲🇽",
    "Brazil": "🇧🇷",
    "Argentina": "🇦🇷",
    "Chile": "🇨🇱",
    "Colombia": "🇨🇴",
    "Peru": "🇵🇪",
    "South Africa": "🇿🇦",
    "Egypt": "🇪🇬",
    "Kenya": "🇰🇪",
    "Nigeria": "🇳🇬",
    "United Arab Emirates": "🇦🇪",
    "Saudi Arabia": "🇸🇦",
    "Israel": "🇮🇱",
    "Turkey": "🇹🇷",
    "Russia": "🇷🇺",
    "Ukraine": "🇺🇦",
  };


  export const CAT_BREEDS = [
    "Domestic Shorthair",
    "Domestic Longhair",
    "Siamese",
    "Persian",
    "Maine Coon",
    "Ragdoll",
    "Bengal",
    "Abyssinian",
    "British Shorthair",
    "Scottish Fold",
    "Sphynx",
    "American Shorthair",
    "Russian Blue",
    "Birman",
    "Oriental",
    "Burmese",
    "Devon Rex",
    "Norwegian Forest Cat",
    "Himalayan",
    "Exotic Shorthair",
    "Cornish Rex",
    "Manx",
    "Tonkinese",
    "Turkish Angora",
    "Balinese",
    "Mixed Breed",
    "Unknown",
  ];


  export const DOG_BREEDS = [
    "Labrador Retriever",
    "German Shepherd",
    "Golden Retriever",
    "French Bulldog",
    "Bulldog",
    "Poodle",
    "Beagle",
    "Rottweiler",
    "German Shorthaired Pointer",
    "Dachshund",
    "Pembroke Welsh Corgi",
    "Australian Shepherd",
    "Yorkshire Terrier",
    "Boxer",
    "Siberian Husky",
    "Great Dane",
    "Doberman Pinscher",
    "Cavalier King Charles Spaniel",
    "Miniature Schnauzer",
    "Shih Tzu",
    "Boston Terrier",
    "Pomeranian",
    "Havanese",
    "Shetland Sheepdog",
    "Brittany",
    "Cocker Spaniel",
    "Border Collie",
    "Chihuahua",
    "Pug",
    "Maltese",
    "Mastiff",
    "Basset Hound",
    "Newfoundland",
    "Rhodesian Ridgeback",
    "West Highland White Terrier",
    "Bernese Mountain Dog",
    "Shiba Inu",
    "Mixed Breed",
    "Unknown",
  ];