-- Seed faq_source with the current PawBuck FAQ list.
-- Run after migration 20260301100000_faq_source_table.sql.
-- Then call add-faq with { "sync": true } to build vectors in faq_documents.

INSERT INTO public.faq_source (question, answer) VALUES
('What is PawBuck?', 'PawBuck is the app that brings everything about your pet into one place — health records, insurance, services, and more. All good things come one step at a time, and we''ve started with what matters most: making your life as a pet parent simpler by organizing all your pet''s health documents. Every pet gets their own email address (like milo@pawbuck.app) that automatically sorts and stores everything the moment it arrives. This is just the beginning — more features are on the way, each one designed to make caring for your pet easier.'),
('How is PawBuck different from other pet apps?', 'PawBuck will eventually be the only app you''ll ever need to care for your pet. But what truly makes us different is where we start — with your pet. Before we recommend anything, we take the time to understand your pet: their health, their history, their needs. That''s why we began with health records. Once we understand your pet, we can recommend the nutrition that''s right for them — not just what''s available on a shelf. We can connect you with the right care provider — not just whoever is nearby. Everything we build starts from knowing your pet, so that every recommendation is personal, not generic. PawBuck also comes with Milo, your AI buddy who learns about your pet to provide you with personalized help along the way.'),
('How does my pet''s email address work?', 'When you create a profile for your pet, they get a unique email address (yourpet@pawbuck.app). Any health document sent to this address is automatically saved, categorized, and added to their health record.'),
('What can I send to my pet''s email?', 'Right now, health documents work best: vet invoices, vaccination certificates, prescriptions, lab results, and medical reports. We''re expanding what PawBuck can process over time.'),
('Does PawBuck read the documents?', 'Yes. PawBuck automatically extracts key information like visit dates, vaccinations, medications, and costs — so you don''t have to enter anything manually.'),
('What if my vet doesn''t use PawBuck?', 'That''s the beauty of it — your vet doesn''t need to. Just ask them to send visit summaries, vaccination PDFs, lab results, and invoices directly to your pet''s PawBuck email, or to CC it. You can also simply forward anything you receive. Either way, PawBuck organizes it all automatically.'),
('What information is stored in my pet''s health profile?', 'Vaccination records, vet visit history, medications, allergies, dietary requirements, microchip number, vet contact information, and all forwarded documents.'),
('Can I add information manually?', 'Yes. You can upload documents, add notes, update details, or add photos anytime in the app.'),
('How do I share my pet''s records?', 'Use the ''Download Pet Passport'' option to create a complete health record you can share with vets, boarders, or caregivers.'),
('What if I don''t have all my pet''s past records?', 'Start fresh and begin forwarding documents from now on. You can request past records from your vet anytime.'),
('How much does PawBuck cost?', 'PawBuck''s core features — your pet''s health record, email address, and document organization — are free. We''ll introduce optional premium features over time.'),
('How do I get started?', 'Download the PawBuck app, create your account, and set up your pet''s profile to receive their unique email address.'),
('Do I need my pet''s microchip number?', 'If you have it, it''s best to add it to your pet''s profile. This allows PawBuck to cross-check that the documents you receive contain the right information for your pet.'),
('Can I manage multiple pets?', 'Yes. Each pet gets their own profile and email address under one account.'),
('Do I need to enter all health information at once?', 'No. You can build your pet''s health history gradually as documents arrive.'),
('What if I already have paper records or PDFs?', 'Email them to your pet''s PawBuck address or upload them directly in the app. PawBuck will organize them automatically.'),
('Is my pet''s data safe?', 'Yes. Your pet''s health records and personal information are stored securely and are never shared with third parties without your permission.'),
('Does PawBuck help with pet insurance?', 'We''re building tools to help you compare insurance options and understand what your pet''s care actually costs. Eventually, PawBuck will even help you file insurance claims automatically — as soon as you complete a vet visit, we''ll have all the requisite documents ready to go. Stay tuned.'),
('Will PawBuck remind me about vaccinations or medications?', 'Yes! PawBuck provides smart reminders on medications as soon as you upload your prescriptions. It also gives you a countdown on your pet''s vaccinations so you always know what''s coming up. We''ll keep improving these features to do a lot more.'),
('Can I delete my data?', 'Yes. You can delete your account and all associated data from within the app at any time.');
