
  create table "public"."daily_medication_schedules" (
    "id" uuid not null default gen_random_uuid(),
    "medication_id" uuid not null default gen_random_uuid(),
    "time" time without time zone not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    "user_id" uuid not null default auth.uid()
      );


alter table "public"."daily_medication_schedules" enable row level security;


  create table "public"."monthy_medication_schedules" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    "day_of_month" smallint not null,
    "time" time without time zone not null,
    "medication_id" uuid not null,
    "user_id" uuid not null default auth.uid()
      );


alter table "public"."monthy_medication_schedules" enable row level security;


  create table "public"."weekly_medication_schedules" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    "medication_id" uuid not null,
    "day_number" smallint not null,
    "time" time without time zone not null,
    "user_id" uuid not null default auth.uid()
      );


alter table "public"."weekly_medication_schedules" enable row level security;

CREATE UNIQUE INDEX daily_medication_schedules_pkey ON public.daily_medication_schedules USING btree (id);

CREATE UNIQUE INDEX monthy_medication_schedules_pkey ON public.monthy_medication_schedules USING btree (id);

CREATE UNIQUE INDEX weekly_medication_schedules_pkey ON public.weekly_medication_schedules USING btree (id);

alter table "public"."daily_medication_schedules" add constraint "daily_medication_schedules_pkey" PRIMARY KEY using index "daily_medication_schedules_pkey";

alter table "public"."monthy_medication_schedules" add constraint "monthy_medication_schedules_pkey" PRIMARY KEY using index "monthy_medication_schedules_pkey";

alter table "public"."weekly_medication_schedules" add constraint "weekly_medication_schedules_pkey" PRIMARY KEY using index "weekly_medication_schedules_pkey";

alter table "public"."daily_medication_schedules" add constraint "daily_medication_schedules_medication_id_fkey" FOREIGN KEY (medication_id) REFERENCES public.medicines(id) not valid;

alter table "public"."daily_medication_schedules" validate constraint "daily_medication_schedules_medication_id_fkey";

alter table "public"."monthy_medication_schedules" add constraint "monthy_medication_schedules_medication_id_fkey" FOREIGN KEY (medication_id) REFERENCES public.medicines(id) not valid;

alter table "public"."monthy_medication_schedules" validate constraint "monthy_medication_schedules_medication_id_fkey";

alter table "public"."weekly_medication_schedules" add constraint "weekly_medication_schedules_medication_id_fkey" FOREIGN KEY (medication_id) REFERENCES public.medicines(id) not valid;

alter table "public"."weekly_medication_schedules" validate constraint "weekly_medication_schedules_medication_id_fkey";

grant delete on table "public"."daily_medication_schedules" to "anon";

grant insert on table "public"."daily_medication_schedules" to "anon";

grant references on table "public"."daily_medication_schedules" to "anon";

grant select on table "public"."daily_medication_schedules" to "anon";

grant trigger on table "public"."daily_medication_schedules" to "anon";

grant truncate on table "public"."daily_medication_schedules" to "anon";

grant update on table "public"."daily_medication_schedules" to "anon";

grant delete on table "public"."daily_medication_schedules" to "authenticated";

grant insert on table "public"."daily_medication_schedules" to "authenticated";

grant references on table "public"."daily_medication_schedules" to "authenticated";

grant select on table "public"."daily_medication_schedules" to "authenticated";

grant trigger on table "public"."daily_medication_schedules" to "authenticated";

grant truncate on table "public"."daily_medication_schedules" to "authenticated";

grant update on table "public"."daily_medication_schedules" to "authenticated";

grant delete on table "public"."daily_medication_schedules" to "postgres";

grant insert on table "public"."daily_medication_schedules" to "postgres";

grant references on table "public"."daily_medication_schedules" to "postgres";

grant select on table "public"."daily_medication_schedules" to "postgres";

grant trigger on table "public"."daily_medication_schedules" to "postgres";

grant truncate on table "public"."daily_medication_schedules" to "postgres";

grant update on table "public"."daily_medication_schedules" to "postgres";

grant delete on table "public"."daily_medication_schedules" to "service_role";

grant insert on table "public"."daily_medication_schedules" to "service_role";

grant references on table "public"."daily_medication_schedules" to "service_role";

grant select on table "public"."daily_medication_schedules" to "service_role";

grant trigger on table "public"."daily_medication_schedules" to "service_role";

grant truncate on table "public"."daily_medication_schedules" to "service_role";

grant update on table "public"."daily_medication_schedules" to "service_role";

grant delete on table "public"."monthy_medication_schedules" to "anon";

grant insert on table "public"."monthy_medication_schedules" to "anon";

grant references on table "public"."monthy_medication_schedules" to "anon";

grant select on table "public"."monthy_medication_schedules" to "anon";

grant trigger on table "public"."monthy_medication_schedules" to "anon";

grant truncate on table "public"."monthy_medication_schedules" to "anon";

grant update on table "public"."monthy_medication_schedules" to "anon";

grant delete on table "public"."monthy_medication_schedules" to "authenticated";

grant insert on table "public"."monthy_medication_schedules" to "authenticated";

grant references on table "public"."monthy_medication_schedules" to "authenticated";

grant select on table "public"."monthy_medication_schedules" to "authenticated";

grant trigger on table "public"."monthy_medication_schedules" to "authenticated";

grant truncate on table "public"."monthy_medication_schedules" to "authenticated";

grant update on table "public"."monthy_medication_schedules" to "authenticated";

grant delete on table "public"."monthy_medication_schedules" to "postgres";

grant insert on table "public"."monthy_medication_schedules" to "postgres";

grant references on table "public"."monthy_medication_schedules" to "postgres";

grant select on table "public"."monthy_medication_schedules" to "postgres";

grant trigger on table "public"."monthy_medication_schedules" to "postgres";

grant truncate on table "public"."monthy_medication_schedules" to "postgres";

grant update on table "public"."monthy_medication_schedules" to "postgres";

grant delete on table "public"."monthy_medication_schedules" to "service_role";

grant insert on table "public"."monthy_medication_schedules" to "service_role";

grant references on table "public"."monthy_medication_schedules" to "service_role";

grant select on table "public"."monthy_medication_schedules" to "service_role";

grant trigger on table "public"."monthy_medication_schedules" to "service_role";

grant truncate on table "public"."monthy_medication_schedules" to "service_role";

grant update on table "public"."monthy_medication_schedules" to "service_role";

grant delete on table "public"."weekly_medication_schedules" to "anon";

grant insert on table "public"."weekly_medication_schedules" to "anon";

grant references on table "public"."weekly_medication_schedules" to "anon";

grant select on table "public"."weekly_medication_schedules" to "anon";

grant trigger on table "public"."weekly_medication_schedules" to "anon";

grant truncate on table "public"."weekly_medication_schedules" to "anon";

grant update on table "public"."weekly_medication_schedules" to "anon";

grant delete on table "public"."weekly_medication_schedules" to "authenticated";

grant insert on table "public"."weekly_medication_schedules" to "authenticated";

grant references on table "public"."weekly_medication_schedules" to "authenticated";

grant select on table "public"."weekly_medication_schedules" to "authenticated";

grant trigger on table "public"."weekly_medication_schedules" to "authenticated";

grant truncate on table "public"."weekly_medication_schedules" to "authenticated";

grant update on table "public"."weekly_medication_schedules" to "authenticated";

grant delete on table "public"."weekly_medication_schedules" to "postgres";

grant insert on table "public"."weekly_medication_schedules" to "postgres";

grant references on table "public"."weekly_medication_schedules" to "postgres";

grant select on table "public"."weekly_medication_schedules" to "postgres";

grant trigger on table "public"."weekly_medication_schedules" to "postgres";

grant truncate on table "public"."weekly_medication_schedules" to "postgres";

grant update on table "public"."weekly_medication_schedules" to "postgres";

grant delete on table "public"."weekly_medication_schedules" to "service_role";

grant insert on table "public"."weekly_medication_schedules" to "service_role";

grant references on table "public"."weekly_medication_schedules" to "service_role";

grant select on table "public"."weekly_medication_schedules" to "service_role";

grant trigger on table "public"."weekly_medication_schedules" to "service_role";

grant truncate on table "public"."weekly_medication_schedules" to "service_role";

grant update on table "public"."weekly_medication_schedules" to "service_role";


  create policy "Policy with security definer functions"
  on "public"."daily_medication_schedules"
  as permissive
  for all
  to public
using ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Policy with security definer functions"
  on "public"."weekly_medication_schedules"
  as permissive
  for all
  to public
using ((( SELECT auth.uid() AS uid) = user_id));



