
  create table "public"."pet_email_whitelist" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "email_id" text not null,
    "pet_id" uuid default gen_random_uuid(),
    "user_id" uuid default auth.uid()
      );


alter table "public"."pet_email_whitelist" enable row level security;

alter table "public"."medicines" add column "custom_frequency_unit" text;

alter table "public"."medicines" add column "custom_frequency_value" integer;

alter table "public"."medicines" add column "last_given_at" timestamp with time zone;

alter table "public"."medicines" add column "next_due_date" timestamp with time zone;

alter table "public"."medicines" add column "reminder_enabled" boolean not null default true;

alter table "public"."medicines" add column "reminder_timing" text default 'Day of'::text;

CREATE UNIQUE INDEX pet_email_whitelist_id_key ON public.pet_email_whitelist USING btree (id);

CREATE UNIQUE INDEX pet_email_whitelist_pkey ON public.pet_email_whitelist USING btree (id);

alter table "public"."pet_email_whitelist" add constraint "pet_email_whitelist_pkey" PRIMARY KEY using index "pet_email_whitelist_pkey";

alter table "public"."pet_email_whitelist" add constraint "pet_email_whitelist_id_key" UNIQUE using index "pet_email_whitelist_id_key";

alter table "public"."pet_email_whitelist" add constraint "pet_email_whitelist_pet_id_fkey" FOREIGN KEY (pet_id) REFERENCES public.pets(id) ON DELETE SET NULL not valid;

alter table "public"."pet_email_whitelist" validate constraint "pet_email_whitelist_pet_id_fkey";

grant delete on table "public"."pet_email_whitelist" to "anon";

grant insert on table "public"."pet_email_whitelist" to "anon";

grant references on table "public"."pet_email_whitelist" to "anon";

grant select on table "public"."pet_email_whitelist" to "anon";

grant trigger on table "public"."pet_email_whitelist" to "anon";

grant truncate on table "public"."pet_email_whitelist" to "anon";

grant update on table "public"."pet_email_whitelist" to "anon";

grant delete on table "public"."pet_email_whitelist" to "authenticated";

grant insert on table "public"."pet_email_whitelist" to "authenticated";

grant references on table "public"."pet_email_whitelist" to "authenticated";

grant select on table "public"."pet_email_whitelist" to "authenticated";

grant trigger on table "public"."pet_email_whitelist" to "authenticated";

grant truncate on table "public"."pet_email_whitelist" to "authenticated";

grant update on table "public"."pet_email_whitelist" to "authenticated";

grant delete on table "public"."pet_email_whitelist" to "service_role";

grant insert on table "public"."pet_email_whitelist" to "service_role";

grant references on table "public"."pet_email_whitelist" to "service_role";

grant select on table "public"."pet_email_whitelist" to "service_role";

grant trigger on table "public"."pet_email_whitelist" to "service_role";

grant truncate on table "public"."pet_email_whitelist" to "service_role";

grant update on table "public"."pet_email_whitelist" to "service_role";


